<?php

/**
 * @file
 * Contains attendance.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function attendance_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the attendance module.
    case 'help.page.attendance':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Attendance allows users to register for event (date-enabled) nodes.') . '</p>';
      return $output;

    default:
  }
}
