<?php

/**
 * @file
 * Contains attendance.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_help().
 */
function attendance_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the attendance module.
    case 'help.page.attendance':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Attendance allows users to register for (event) nodes.') . '</p>';
      $output .= '<p>' . t('Create attendance types (like "guests" or "vip") and choose node types to attend to (usually event nodes).<br/>
        Place the corresponding form block in the block layout. Make sure it shows up in node pages.<br/>
        The form block should be visible to users with the permission to add attendance entries for that attendance type.<br/>
        There are also public attendance listing blocks available.
        ') . '</p>';
      $output .= '<p>' . t('The node owner should be able to see the attendance report as a tab under their node page.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function attendance_theme() {
  $theme = [];
  $theme['attendance'] = [
    'render element' => 'elements',
    'file' => 'attendance.page.inc',
    'template' => 'attendance',
  ];
  $theme['attendance_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'attendance.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function attendance_theme_suggestions_attendance(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#attendance'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'attendance__' . $sanitized_view_mode;
  $suggestions[] = 'attendance__' . $entity->bundle();
  $suggestions[] = 'attendance__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'attendance__' . $entity->id();
  $suggestions[] = 'attendance__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
