attendance.attendance_type.*:
  type: config_entity
  label: 'Attendance type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    target_bundle:
      type: string
      label: 'Target node type'
    target_field:
      type: string
      label: 'Target field for geofencing'
    distance:
      label: 'Distance limit for geofencing'
      type: integer
