attendance.attendance_type.*:
  type: config_entity
  label: 'Attendance type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    node_type:
      type: string
    field:
      type: string
    distance:
      type: integer
